### PR TITLE
Implement debug trait with nightly trivial_bounds feature

### LINKED ISSUE #26: MultiIndexMap should derive Debug, when inner type derives Debug
When the struct, where the derive macro `#[derive(MultiIndexMap)` is added, also derives the `Debug` trait, the generated MultiIndexMap should also derive the `Debug` trait.

As far as I can tell, this is currently not possible, but could be when specialization is stabilized:
https://github.com/dtolnay/syn/issues/77#issuecomment-272985262

But maybe you have another idea how to implement this feature already!

### PR DESCRIPTION
**Pull request by luxbe**
This fixes #26, by generating a Debug trait automatically with the required Debug bounds.

Open points:
- Should this feature be under a more specific feature flat (e.g. experimental-debug) for more clarity?
- This addition is not the cleanest. There are multiple duplicate parts in the code that could be cleaned up. Should this be done here or in a new PR?

Let me know what you think and if there are further changes that should be made!

### CODE REVIEW

**Comment by lun3x** [comment]
Thanks for this! Yeah I agree, maybe even just call the feature `trivial_bounds`, I could see other possibilities with this unstable feature (eg. allowing non-Clonable elements by not implementing modify_by_ methods when the element doesn't implement Clone), and maybe it's best to link them together for if/when this nightly feature gets stabilised.

If you wanna do them here that's fine by me! I can just diff the changes from the current commit.

**Comment by luxbe** [comment]
The implementation should be ready now. This PR also brings the branch up to date with the master branch so you can easily merge it back into master. 

I renamed the feature to `trivial_bounds` as you suggested and removed some duplicate code I mentioned before (see `index_field_type` method in `generators.rs`). I also cleaned up the implementation so that the debug parts are only compiled when the `trivial_bounds` feature is enabled.

Let me know what you think!

**Comment by lun3x** [comment]
Nice, looks good, I'll merge to my trivial_bounds branch, then over to master! Just one stray commented out line, and I'll change the `core::fmt::Debug` to `::core::fmt::Debug` for macro hygiene, but I can do that easily in my branch

**Comment by luxbe** [comment]
Good catch! Thanks :)

**Pull request merged**
